USE master
CREATE DATABASE BankSystem
GO

USE BankSystem

CREATE TABLE dbo.Banks(
	BankID INT PRIMARY KEY IDENTITY(1,1),
	Name NVARCHAR(64) NOT NULL
)

CREATE TABLE dbo.Cities(
	CityID INT PRIMARY KEY IDENTITY(1,1),
	Name NVARCHAR(64) NOT NULL
)

CREATE TABLE dbo.BranchOffices(
	BranchOfficeID INT PRIMARY KEY IDENTITY(1,1),
	Name NVARCHAR(64) NOT NULL,
	CityID INT NOT NULL,
	BankID INT NOT NULL,
	FOREIGN KEY (CityID) REFERENCES Cities(CityID),
	FOREIGN KEY (BankID) REFERENCES Banks(BankId)
)

CREATE TABLE dbo.SocialStatuses(
	SocialStatusID INT PRIMARY KEY IDENTITY(1,1),
	Name NVARCHAR(32) NOT NULL
)

CREATE TABLE dbo.Clients(
	ClientID INT PRIMARY KEY IDENTITY(1,1),
	Name NVARCHAR(256) NOT NULL,
	Phone NVARCHAR(16) NOT NULL,
	SocialStatusID INT NOT NULL,
	FOREIGN KEY (SocialStatusID) REFERENCES SocialStatuses(SocialStatusID)
)

CREATE TABLE dbo.BankClients(
	ID INT PRIMARY KEY IDENTITY(1,1),
	BankID INT NOT NULL,
	ClientID INT NOT NULL,
	FOREIGN KEY (BankID) REFERENCES Banks(BankID),
	FOREIGN KEY (ClientID) REFERENCES Clients(ClientID) ON DELETE CASCADE
)

CREATE TABLE dbo.BankAccounts(
	BankAccountID INT PRIMARY KEY IDENTITY(1,1),
	ClientID INT NOT NULL UNIQUE,
	AccountBalance DECIMAL(18, 4) NOT NULL,
	FOREIGN KEY (ClientID) REFERENCES Clients(ClientID)
)

CREATE TABLE dbo.BankCards(
	BankCardID INT PRIMARY KEY IDENTITY(1,1),
	BankAccountID INT NOT NULL,
	CardBalance DECIMAL(18, 4) NOT NULL,
	FOREIGN KEY (BankAccountID) REFERENCES BankAccounts(BankAccountID)
)