USE master
CREATE DATABASE BankSystem
GO

USE BankSystem

CREATE TABLE Banks(
	Id INT PRIMARY KEY IDENTITY(1,1),
	Name NVARCHAR(64) NOT NULL
)

CREATE TABLE Cities(
	Id INT PRIMARY KEY IDENTITY(1,1),
	Name NVARCHAR(64) NOT NULL
)

CREATE TABLE BranchOffices(
	Id INT PRIMARY KEY IDENTITY(1,1),
	Name NVARCHAR(64) NOT NULL,
	CityId INT NOT NULL,
	BankId INT NOT NULL,
	FOREIGN KEY (CityId) REFERENCES Cities(Id),
	FOREIGN KEY (BankId) REFERENCES Banks(Id)
)

CREATE TABLE SocialStatuses(
	Id INT PRIMARY KEY IDENTITY(1,1),
	Name NVARCHAR(32) NOT NULL
)

CREATE TABLE Clients(
	Id INT PRIMARY KEY IDENTITY(1,1),
	Name NVARCHAR(256) NOT NULL,
	Phone NVARCHAR(16) NOT NULL,
	SocialStatusId INT NOT NULL,
	FOREIGN KEY (SocialStatusId) REFERENCES SocialStatuses(Id)
)

CREATE TABLE BankClients(
	Id INT PRIMARY KEY IDENTITY(1,1),
	BankId INT NOT NULL,
	ClientId INT NOT NULL,
	AccountBalance DECIMAL(18, 4) NOT NULL,
	UNIQUE (BankId, ClientId),
	FOREIGN KEY (BankId) REFERENCES Banks(Id),
	FOREIGN KEY (ClientId) REFERENCES Clients(Id) ON DELETE CASCADE
)

CREATE TABLE BankCards(
	Id INT PRIMARY KEY IDENTITY(1,1),
	BankClientId INT NOT NULL,
	CardBalance DECIMAL(18, 4) NOT NULL,
	FOREIGN KEY (BankClientId) REFERENCES BankClients(Id)
)